# Generated by Django 4.2.6 on 2024-11-24 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DepositProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fin_prdt_cd", models.TextField(unique=True)),
                ("kor_co_nm", models.TextField()),
                ("fin_prdt_nm", models.TextField()),
                ("etc_note", models.TextField()),
                ("join_deny", models.IntegerField()),
                ("join_member", models.TextField()),
                ("join_way", models.TextField()),
                ("spcl_cnd", models.TextField()),
                ("mtrt_int", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SavingProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fin_prdt_cd", models.TextField(unique=True)),
                ("kor_co_nm", models.TextField()),
                ("fin_prdt_nm", models.TextField()),
                ("etc_note", models.TextField()),
                ("join_deny", models.IntegerField()),
                ("join_member", models.TextField()),
                ("join_way", models.TextField()),
                ("spcl_cnd", models.TextField()),
                ("mtrt_int", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SavingPopularity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("popularity", models.IntegerField(default=0)),
                ("click_count", models.IntegerField(default=0)),
                ("view_time_count", models.IntegerField(default=0)),
                ("purchase_count", models.IntegerField(default=0)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="popularity",
                        to="products.savingproducts",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavingOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fin_prdt_cd", models.TextField()),
                ("intr_rate_type_nm", models.TextField()),
                ("intr_rate", models.FloatField(null=True)),
                ("intr_rate2", models.FloatField(null=True)),
                ("save_trm", models.IntegerField(null=True)),
                ("rsrv_type_nm", models.TextField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="products.savingproducts",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DepositPopularity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("popularity", models.IntegerField(default=0)),
                ("click_count", models.IntegerField(default=0)),
                ("view_time_count", models.IntegerField(default=0)),
                ("purchase_count", models.IntegerField(default=0)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="popularity",
                        to="products.depositproducts",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DepositOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fin_prdt_cd", models.TextField()),
                ("intr_rate_type_nm", models.TextField()),
                ("intr_rate", models.FloatField(null=True)),
                ("intr_rate2", models.FloatField(null=True)),
                ("save_trm", models.IntegerField(null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="products.depositproducts",
                    ),
                ),
            ],
        ),
    ]
