# Generated by Django 4.2.6 on 2024-11-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_depositoptions_intr_rate_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='finance_product',
        ),
        migrations.AddField(
            model_name='user',
            name='joined_deposits',
            field=models.ManyToManyField(blank=True, related_name='joined_users', to='products.depositproducts'),
        ),
        migrations.AddField(
            model_name='user',
            name='joined_savings',
            field=models.ManyToManyField(blank=True, related_name='joined_users', to='products.savingproducts'),
        ),
    ]
